// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAANKw_StIXHfut-fyW202suSOaANOsXGg',
    appId: '1:512806333930:web:84c5677dfa5de0fef25693',
    messagingSenderId: '512806333930',
    projectId: 'olx-clone-tr',
    authDomain: 'olx-clone-tr.firebaseapp.com',
    storageBucket: 'olx-clone-tr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpafjTYL4SgSfQF3y4ty9nybNdkAkaFk',
    appId: '1:512806333930:android:ea1a779bf56ea035f25693',
    messagingSenderId: '512806333930',
    projectId: 'olx-clone-tr',
    storageBucket: 'olx-clone-tr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI2ReNR89CXzrGfxVq7pFHyarHiQmuuWk',
    appId: '1:512806333930:ios:45ef09c9c5112f30f25693',
    messagingSenderId: '512806333930',
    projectId: 'olx-clone-tr',
    storageBucket: 'olx-clone-tr.appspot.com',
    iosBundleId: 'com.example.olx',
  );
}
